In [1]:
import numpy as np

print(np.__version__)

2.3.2


In [2]:
arr = np.array([1,6,4,3,3,7])
print(arr)
print(type(arr))

[1 6 4 3 3 7]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

arr = np.array([
    [[1,6,4,38,3,7], [1,6,5,38,3,7]],
    [[1,6,4,38,3,7], [1,9,5,38,3,7,]]])
print(arr)
print(type(arr))
print(arr.shape)

print(arr[1][1][1])

[[[ 1  6  4 38  3  7]
  [ 1  6  5 38  3  7]]

 [[ 1  6  4 38  3  7]
  [ 1  9  5 38  3  7]]]
<class 'numpy.ndarray'>
(2, 2, 6)
9


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr.sum())


# basics functions of numpy
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr)) # std * std
print(np.prod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))
print(np.diff(arr))
print(np.nonzero(arr))
print(np.sort(arr))
print(np.argsort(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.zeros([5,5])) # numpy array
print("\n\n")

print(np.identity(4))

print(np.eye(5))

In [ ]:
print(np.eye(5, k =1))

In [ ]:
# rand function
# print(np.random.randn(2))
# print(np.random.randint(1000))

arr = np.array([
    [11,22,33],
    [44,55,66],
    [77,88,99]
])

x = arr[:3,0:2]

y = arr[0:3,2]

print(x)
print(y)



In [ ]:
# arrange function
np.arange(15).reshape(5,3)

In [85]:
# Broadcasting

arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# matrix multiplicationa
import numpy as np

a = np.array([[1,2,3],[2,3,4]])
b = np.array([[1,2],[2,3],[3,4]])

print(np.dot(a,b))
print(a @ b)
print(np.matmul(a,b))

[[14 20]
 [20 29]]
[[14 20]
 [20 29]]
[[14 20]
 [20 29]]


In [6]:
# Transpose 

A = np.array([[1,2,3],[4,5,6]])
print(A.T)

print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [8]:
# linear algebra

a = np.array([[1,2,-1],[2,1,1],[3,-1,2]])
b= np.array([3,7,4])
print(np.linalg.solve(a,b))


[-5.92118946e-16  3.33333333e+00  3.66666667e+00]


In [9]:
#determinent of a matrix

d = np.array([[1,2],[3,4]])
print(np.linalg.det(d))

-2.0000000000000004


In [11]:
#Inverse of a matrix

d = np.array([[1,2,3],[3,4,6], [7,8,9]])
print(np.linalg.inv(d))

[[-2.00000000e+00  1.00000000e+00  1.26882631e-16]
 [ 2.50000000e+00 -2.00000000e+00  5.00000000e-01]
 [-6.66666667e-01  1.00000000e+00 -3.33333333e-01]]


In [13]:
# Trace of a matrics =  sum of a diagnal of a square matrix


d = np.array([[1,2,3],[3,4,6], [7,2,9]])
print(np.trace(d))

14


In [15]:
#linespace

values = np.linspace(1,10,num=10)
print(values)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [22]:
# empty function

d = np.empty((3,3), dtype =int)
print(d)

[[1 2 3]
 [3 4 6]
 [7 8 9]]


In [24]:
# flattened array to create a 1d array

d = np.array([[1,2,3],[3,4,6], [7,2,9]])
flt_arr = d.flatten()

print(d)
print(flt_arr)

[[1 2 3]
 [3 4 6]
 [7 2 9]]
[1 2 3 3 4 6 7 2 9]


In [25]:
# ravel similarly to flatten but more efficient memory
d = np.array([[1,2,3],[3,4,6], [7,2,9]])
rav_arr = d.ravel()

print(d)
print(rav_arr)


[[1 2 3]
 [3 4 6]
 [7 2 9]]
[1 2 3 3 4 6 7 2 9]


In [ ]:
# hstack() function
d = np.array([[1,2,3],[3,4,6], [7,2,9]])
b = np.array([[1,2,3],[3,4,6], [7,2,10]])

print(np.hstack((d,b)))

# vstack()
print(np.vstack((d,b)))


[[ 1  2  3  1  2  3]
 [ 3  4  6  3  4  6]
 [ 7  2  9  7  2 10]]
[[ 1  2  3]
 [ 3  4  6]
 [ 7  2  9]
 [ 1  2  3]
 [ 3  4  6]
 [ 7  2 10]]
